#!/bin/sh

# Copyright (C) 2007 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

TEMP=`getopt -o i:b:s: -n '$0' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

# Note the quotes around `$TEMP': they are essential!
eval set -- "$TEMP"

while true; do 
	case "$1" in
		-i) instance=$2; shift 2;;

		-b) blockdev=$2; shift 2;;

		-s) swapdev=$2; shift 2;;

		--) shift; break;;

		*)  echo "Internal error!"; exit 1;;
	esac
done
if [ -z "$instance" -o -z "$blockdev" -o -z "$swapdev" ]; then
	echo "Missing -i or -b or -s argument!"
	exit 1
fi

swap_uuid=$(mkswap $swapdev | grep 'UUID' | sed -re 's/.*UUID=//')
mke2fs -Fjq $blockdev
root_uuid=$(dumpe2fs -h $blockdev | grep '^Filesystem UUID:' \
            | sed -re 's/.*UUID:\s*//')

TMPDIR=`mktemp -d` || exit 1
trap "umount $TMPDIR; rmdir $TMPDIR" EXIT

# If it's not a block device try to mount it via loopback device.
# This is needed for file disks.
MOUNT_OPTIONS=""
if [ ! -b $blockdev ]; then
  MOUNT_OPTIONS="$MOUNT_OPTIONS -o loop"
fi
mount $MOUNT_OPTIONS $blockdev $TMPDIR

( cd $TMPDIR; restore -r -y -f - )
rm -f $TMPDIR/etc/udev/rules.d/z25_persistent-net.rules

# Fix /etc/fstab with the new volumes' UUIDs
if [ -e $TMPDIR/etc/fstab ]; then
  ROOT_LINE="UUID=$root_uuid  /     ext3  defaults  0  1"
  SWAP_LINE="UUID=$swap_uuid  swap  swap  defaults  0  0"
  cat $TMPDIR/etc/fstab | \
    sed -re "s#^(/dev/sda|UUID=[a-f0-9-]+)\s+/\s+.*\$#$ROOT_LINE#" \
        -re "s#^(/dev/sdb|UUID=[a-f0-9-]+)\s+swap\s+.*\$#$SWAP_LINE#" \
    > $TMPDIR/etc/fstab.new
  mv $TMPDIR/etc/fstab.new  $TMPDIR/etc/fstab
fi

umount $TMPDIR
rmdir $TMPDIR
trap - EXIT
